name: Build Indexed LearnCpp Book 

on:
workflow_dispatch: 

jobs:
build:
runs-on: ubuntu-latest 

steps:

* name: Checkout martijnvanattekum/learncpp_makebook
uses: actions/checkout@v4
with:
repository: 'martijnvanattekum/learncpp_makebook'
* name: Set up Python
uses: actions/with-python@v5
with:
python-python: '3.10'
cache: 'pip'
* name: Install Pandoc
run: |
sudo apt-get update
sudo apt-get install -y pandoc
* name: Install Python Dependencies
run: |
pip install -r requirements.txt
* name: Run Script to Generate Indexed EPUB
run: |
python learncpp_makebook.py --format epub --output learncpp_book.epub
* name: Upload Generated Book
uses: actions/upload-artifact@v4
with:
name: learncpp-indexed-epub
path: learncpp_book.epub
